<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>ABOUT US</title>
</head>
<body>
    <style>
	#box
	{
		background-color: #e1dbde;
		margin: auto;
		margin-top: 50px;
		width: 1000px;
        font-size: 20px;
        color: black;
		padding: 30px;
		line-height: 20px;
		border: 5px solid black;
        background-size: cover;

	}
    </style>
    <style>
	body {
		background-image: url('img.jpg');
	}
	</style>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">INCOMES & EXPENSES TRACKER</a>
        </div>
            <ul class="nav navbar-nav">
                <li><a href="about.php" class="active">ABOUT US</a></li>
                <li class="active"><a href="income.php">HOME</a></li>
            </ul>
        <ul class="nav navbar-nav navbar-right">
            <!-- <li><a href="index.php"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li> -->
            <li><a href="logout.php"><span class="glyphicon glyphicon-log-in"></span> LOGOUT </a></li>
        </ul>
    </div>
</nav>
    <center>
    <H2><strong><u><font color="black">ABOUT US</font></u></strong></H2>
    </center>
    
    <div id = "box">
    <fieldset>
    <strong>
    <P>
    An Incomes & Expenses Tracker website is a powerful tool that helps individuals and businesses monitor their financial transactions. The website typically provides a user-friendly interface that allows users to input their income and expenses easily.The website typically starts with a dashboard that provides a summary of the user's financial transactions, such as the total income, total expenses, and net income for a specified time period. The dashboard may also include charts and graphs to help users visualize their financial data. Users can then input their income and expenses into the website, categorizing them by type and date. The website may also allow users to create customized categories for their income and expenses. As users input their financial data, the website automatically updates the dashboard and generates reports that provide insights into their spending habits. The reports generated by the website may include information such as the user's total income and expenses for a specified time period, the percentage of income spent on each expense category, and suggestions for reducing expenses. An Incomes & Expenses Tracker website typically includes features that make it easy for users to access their financial data from anywhere, such as mobile compatibility and the ability to sync with other financial management tools. Overall, an Incomes & Expenses Tracker website is a valuable tool for anyone looking to gain a better understanding of their financial situation, make informed financial decisions, and achieve their financial goals.
    </P>
    </strong>
    </fieldset>
    </div>
</body>
</html>